name: Run Scripts

on:
  schedule:
    - cron: '30 6 * * *'  # Run daily at 6.30 am
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: node src/local.cjs